### ISSUE TITLE
1장 지식 탐구

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#1]

**Comment by chanhyeong** [comment]
domain 과 model 은 무엇이고
domain model 은 무엇인가

- 사용자의 활동이나 관심사
- 지식을 단순화하고 구조화 한 것
- 다이어그램이 전달하고자 하는 아이디어

---

### 지식 탐구 (Knowledge Crunching)
- 효과적으로 도메인 모델링을 수행하는 과정
  - 지속적인 정제
  - 애자일인가?
- 지속적인 학습
  - 스스로 학습하는 팀원: 가장 핵심적인 부분을 개발하는 데 초점을 맞춘 고정 핵심 인력을 형성

**Comment by y2o2u2n** [comment]
**도메인**

사용자가 프로그램을 사용하는 대상 영역이 바로 해당 소프트웨어의 도메인이다.

**지식 탐구**

많은 정보를 바탕으로 모델 간 관련성을 찾고 간결한 모델을 시도해보고 버리고 바꾼다.
모든 세부 사항을 만족하는 추상적 개념이 나타나면 이 작업은 완료된다.

**지속적인 학습**

팀 구성원이나 개발자, 도메인 전문가에게서 모두 똑같이 지식을 얻고 의사 소통 체계를 공유하며, 구현을 거쳐 피드백 고리를 완성하는 일이 중요하다.

**Comment by y2o2u2n** [comment]
사용자가 프로그램을 사용하는 대상 분야를 도메인이라고 한다.
모델이란 대상을 단순화해서 표현한 것이다.
도메인 모델이란 사용자가 프로그램을 사용하는 대상 영역에 관한 진식을 선택적으로 단순화하고 의식적으로 구조화한 형태다.

From 객체지향의 사실과 오해
