### ISSUE TITLE
10장 유연한 설계

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#11]

**Comment by y2o2u2n** [comment]
# 이번 장은...

- 유연한 설계를 위해서 특별한 공식은 없지만 적용하기 괜찮은 패턴을 소개하는 장
- 개인적으로 읽으면서 TDD 의 중요성을 다시 한번 생각하게 되는 장

# 의도를 드러내는 인터페이스

클래스와 연산의 이름을 지을 때...

- 수행 방법은 언급하지 않기
- 결과와 목적만을 표현하기
- 유비쿼터스 언어에 포함된 용어만 쓰기
- 클래스와 연산을 추가하기 전에 **행위에 집중**하기

> 테스트 코드 먼저 작성하면, 행위에 먼저 집중할 수 있었던 것 같음

# 부수효과가 없는 함수

- 가능한 한 부수효과 없이 결과를 반환하는 함수를 작성하기
- 명령을 도메인 정보를 반환하지 않는 아주 단순한 연산으로 분리하기
- 연산의 결과를 표현하는 새로운 **값객체를 활용**하기

# 단언

- 연산의 사후조건과 클래스 및 어그리게이트의 불변식을 명시하기 (ex. 적절하지 않을때 예외 던지기?)
- 테스트에서 단언으로 검증하기

> 요구사항을 잘 정리해서 모든 케이스를 테스트 코드로 작성해두면 나중에 변경을 대비해서 좋은 준비가 되는 것 같음

# 개념적 윤곽

> 뒤죽박죽이면 의미를 파악하기 힘들어서 문제이고, 너무 잘게 쪼개도 복잡해져서 문제이니
적절하게 객체가 협력하도록 해야한다는데,,,
실천적인 내용이 이해가 잘 가지 않음 ㅠ

# 독립형 클래스

- 가능한 결합도를 낮추기
- 현재 상관과 무관한 모든 개념 제거하기

# 연산의 닫힘

- 연산을 정의할 때 해당 타입의 인스턴스 집합에만 닫혀있도록 설계
- 주로 값객체의 연산을 정의하는데 주로 사용됨

> 자연수 클래스 NaturalNumber 가 있다고 할 때 덧셈을 구현한다 치면
밖의 클래스에서 NaturalNumber 안의 값을 꺼내서 더하지 않고
NaturalNumber 클래스 내에서 값을 계산해서 새로운 값객체를 반환하는 식?

```
public class NaturalNumber {
    private final int value;

    private NaturalNumber(int number) {
        this.value = number;
    }

    public static NaturalNumber add(NaturalNumber x, NaturalNumber y) {
        return new NaturalNumber(x.value + y.value);
    }
}
```

# 선언적 설계

- 실행 가능한 명세로서 프로그램을 작성하는 일
- SPECIFICATION 을 선언적으로 확장하는 예시를 살펴봄

# 예시

- 명령과 질의가 합쳐져 있을 때 분리한다.
- 암시적인 개념을 명확하게 만든다.
- 가능하면 값 객체로 만들고 ASSERTION 을 정의한다.
- 연산이 해당 타입일 때만 닫혀있도록 한다.

**Comment by youngvly** [comment]
![IMG_1246](https://user-images.githubusercontent.com/19251378/128884451-fac8f270-a1c7-4b9b-b5ba-5b75f5d9902c.jpeg)



### 선언적(declarative) 
- 어떤 방법 (how)으로 해야하는지 보다, 무엇과 같은지(what)를 설명하는 경우
- = 목표를 명시하고, 알고리즘은 명시하지 않는것.
    - 예시:  HTML, 화면에 무엇이 나타나야하는지 묘사 / SQL
    - 반대 예시 : 명령형 프로그래밍 (ex_ java, c,,) 알고리즘을 명시
- 명령형 프로그래밍이라도, 함수형, 논리형,제한형 프로그래밍으로 표현되면 선언적이라 볼 수 있음.

[정리잘돼있다](https://medium.com/@hongseongho/%EC%84%A0%EC%96%B8%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-1d8247342f17)

### DSL
예시 : SQL, css,,

**Comment by chanhyeong** [comment]
### INTENTION-REVEALING INTERFACE
문제를 내고, 푸는 방법을 표현하면 안됨

### SIDE-EFFECT-FREE FUNCTION
command 를 도메인 정보를 반환하지 않는 단순한 연산으로 분리
책임에 적합한 개념이 나타나면 로직을 Value Object 로 옮겨 side effect 를 통제

### ASSERTION
기존에 사용하던 requireNonNull, assertEquals 이런 개념인 것 같은데

예시가 이해가 잘 안됨. 갑자기 왜 분리하는지

### CONCEPTUAL CONTOUR
새로 알게 된 개념이나 요구사항을 코드에 적용
- 이 개념이 현재 모델과 코드에 포함된 관계를 기준으로 했을 때 적절한가?
- 현재 기반을 이루는 도메인과 유사한 윤곽을 나타내는가?

반복적인 리팩토링으로 유연한 설계
- 설계 요소 (operation, interface, class, aggregate) 를 응집력 있는 단위로 분해
- 변경되는 부분과 변경되지 않는 부분을 나누는 것을 식별
  - 변경을 분리하기 위한 패턴을 명확하게 표현하는 CONCEPTUAL CONTOUR 를 찾을 것

예시에서 나온 CONCEPTUAL CONTOUR 는 Payment 인가?
(조기 상환 및 연체 상환 처리 규칙이 추가되는 과정에서 여기에 개념이 들어감)

---
중간 정리
> INTENTION-REVEALING INTERFACE: 클라이언트에 의미 단위로 객체를 제공하게 해줌
> SIDE-EFFECT-FREE FUNCTION, ASSERTION: 위를 사용한 복잡한 조합을 만드는 일을 안전하게
> CONCEPTUAL CONTOUR: 모델의 각 부분이 안정화되고, 단위를 직관적으로 사용하고 조합할 수 있게 됨
---

### STANDALONE CLASS
- 결합도 낮추기 = 의존성 최대한 제거
- 같은 모듈에 속하는 클래스 간 의존성은 외부보다는 문제가 적음
- 복잡한 계산을 VALUE OBJECT 로 도출

### CLOSURE OF FUNCTION
return type 과 parameter type 이 동일한 연산 정의

### Declarative design
DSL
따로 있는게 아니고 우리가 정의할 수 있음

### Angles of Attack (받음각.. ㅋㅋ)
- 하위 도메인으로 분할하기 (15장에서 상세하게)
- 정립된 정형화 (Established Formalisms) 활용
  - 도메인 어딘가의 수학적인 개념을 찾아 분할

---

드디어 절반을 넘음
읽으면서 정리가 잘 안되네요....

**Comment by bearics** [comment]
### 연산의 닫힘
- 반환 타입과 인자 타입이 동일한 연산을 정의하라  
라고 되어 있는데, 
```
Class Person { 
  private int age;
}

Class PeopleGroup {
  private List<Person> people;

  // 이런 로직들도 닫히도록 짜야할까요??
  private List<Person> getOlderPeople(Person person) {  // 이런것도 닫혔다고 보는건가??
     return people.filter(e -> e.age > person.age).collect();
  }

  private List<Person> getOlderPeople(int tagetAge) {
     return people.filter(e -> e.age > tagetAge).collect();
  }
}
```

### COMMAND와 SIDE-EFFECT-FREE FUNCTION의 분리 p304
COMMAND, QUERY를 분리해서 결과적으로
```
Map distribution = aLoan.calculatePrincipalPaymentShares(paymentAmount);  // 배분할 금액 계산 == query
aLoan.applyPrincipalPaymentsShares(distribution);  // 상태 변경  == command
```
이렇게 되면 해당 코드 2줄은 어디에 있는게 좋을까요?? 응용 서비스 계층 OR 도메인 서비스 계층.

### Value Object의 역할이 생각보다 크구나라고 느낌
VO는 단순 값객체로 보았는데, 해당 객체에도 로직이 포함되는거를 보고 생각보다 역할이 크다고 느낌.
ENTITY랑 다른 점은 상태가 변경되지 않고 매번 새로운 객체가 생김.
