### ISSUE TITLE
15장 디스틸레이션

### ISSUE THREAD

**Issue by bearics** [juniors-dev-study/domain-driven-design#17]
## Distillation 
: 혼합된 요소를 분리해서 본질을 좀더 값지고 유용한 형태로 뽑아가는 과정
![image](https://user-images.githubusercontent.com/19251378/132480834-e92b173f-3596-4ca6-933e-5e04c38b6398.png)

## CORE DOMAIN 핵심도메인
: 애플리케이션 모델의 중심적인 모델
- 설계가 복잡하다는 신호 : 자신의 업무(도메인)을 한정적으로 하면 팀간의 지식전달이 줄어듦 > 코드 중복 발생 > 시스템 복잡도 증가 ..! (현상황..?)
- CORE를 추출해내는 작업은 도메인 지식이 많은 능력있는 개발자와 여러 도메인 전문가가 해야한다. 
- CORE DOMAIN 을 프레임워크식으로 구입하는것은 바람직하지않다.

## GENERIC SUBDOMAIN : 일반 하위 도메인
: 현재 진행중인 프로젝트를 위한것이 아닌, 응집력있는 하위 도메인을 식별하라.
- 하위 도메인에서 일반화된 모델요소를 추출해서 별도 MODULE에 배치하라.
- CORE DOMAIN 보다 우선순위를 낮게하고, 핵심개발자를 배치하지 않는다.
- 일반화가 재사용 가능하다는 의미는 아니다. : 재사용을 목적으로 SUB DOMAIN을 개발하는것은, 디스틸레이션의 기본동기에 어긋난다.
- 애자일 프로세스에서는 일반적으로 가장 위험스러운 업무를 먼저 다루는 식으로 위험을 관리할 것을 요구한다.
- 구현방식 : 기성솔루션  / 공표된 모델(분석패턴) / 외주 / 사내구현

## DOMAIN VISION STATEMENT 도메인 비전 선언문
: 핵심 도메인을 짧게 기술하고, 그것이 가져올 가치에 해당하는 '가치제안'을 작성하라. (약 한페이지분량)
> ex ) 모델은 프로세스에 필요한 인력자원을 포함하지는 않지만, 공정방법을 내려받아 선택적인 프로세스 자동화가 가능해야한다.

## HIGHLIGHTED CORE 강조된 핵심 <디스틸레이션 문서>
: CORE DOMAIN과 CORE의 구성요소 사이에서 일어나는 상호작용을 기술하는 간결한 문서작성하라.(3~7p분량)
- UML, 시퀀스 다이어그램, 비표준 다이어그램 등등.. 비기술팀원도 이해할수 있는 수준이어야 한다.
- 디스틸레이션 문서가 CORE DOMAIN의 본직적인 면면의 윤곽을 드러낸다면, 모델 변경의 중요성을 나타내는 실질적인 지표로 활용될수있다.
- 모델이나 코드변경이 문서에 영향을 주면, 다른팀원과 상의가 필요하며, 새 문서를 배포해야한다.

## COHENSIVE MECHANISM 응집력있는 메커니즘
: 개념적으로 응집력있는 매커니즘을 별도 경량 프레임워크로 분할하라. (특히 잘 문서화된 알고리즘)
- 매커니즘 자체가 기업 소유이고, 소프트웨어 가치의 핵심부분인 경우 CORE에 남아있을 수 있다.
#### GENERIC SUBDOMAIN 과 COHENSIVE MECHANISM
- 둘다 핵심 도메인의 부담을 더는것에 목적이 있다.
- GENERIC SUBDOMAIN : 핵심 도메인의 덜 중심적이고, 덜 중요한 일부 측면.
- COHENSIVE MECHANISM : 일부 계산문제를 해결해줄 뿐. (유틸성?)
> 일반 하위도메인은 코어에서 분리한거고,,도메인이니 도메인 규칙은 있는거고, 메커니즘은,, 정말 계산만? 알고리즘?

## SEGREGATED CORE 분리된 핵심
: 일반적이거나 보조적인 역할을 하는 하는 구성요소를 다른 객체로 추출해서 다른 패키지에 배치하라.
> 그럼 이게 새로운 CORE DOMAIN이 되는건가??
#### 화물 해운 모델 예시
1. DOMAIN VISION STATEMENT를 살펴보니, 결제와 관련된 역할은 보조적인것에 불구하므로, Billing 패키지를 분리한다.
2. 화물인도,취급이 가장 중요하므로 Delivery 를 분리해 SEGREGATED CORE로 만든다.
3. '고객계약' 객체의 역할이 '고객' 객체의 역할을 대신하게 되었으므로, 'Customer' 도메인을 분리할 수 있다.
4. 'Delivery' : SEGREGATED CORE / 'BILLING' : GENERIC SUBDOMAIN / 'Customer' , 'Shipping' : 모듈로 분리

## ABSTRACT CORE 추상화된 핵심
: 모델의 가장 근본적인 개념을 식별해서 그것을 별도의 클래스나 추상클래스, 또는 인터페이스로 추출하라. 
- 이는 상호작용을 대부분 표현할 수 있게끔 설계되어야 한다.
- 결국 디스틸레이션 문서와 비슷해 보일 것이다.
> 일반 하위도메인 간의 상호작용을 인터페이스를 통해 하라는건가??? 예시를 봐야 이해가 될둣..

## 리팩터링 대상의 선택
1순위는 CORE DOMAIN , 분해하고 CORE의 격리를 개선하는등 디스틸레이션 해본다.
2순위는 CORE와 지원요소와의 관계가 관련되어있는 곳.

**Comment by chanhyeong** [comment]
### CORE DOMAIN
애플리케이션의 목적에 중심적인 모델

CORE DOMAIN 을 찾아서 support 하는 모델과 코드로부터 분리, 작게 유지

#### 누가 ?
기술적인 팀원이 도메인 지식을 갖춘 경우는 거의 없다 - 도메인 지식을 보조 컴포넌트로 배정하는 경향
오랜 기간 팀에 참여하고 도메인 지식에 관심있는 능력있는 개발자 + 업무를 깊이 알고 있는 도메인 전문가

### GENERIC SUBDOMAIN
전문 지식이 아닌 복잡성을 더하는 모델, 부수적인 요소

진행 중인 프로젝트를 위한 것이 아닌 응집력 있는 하위 도메인
-> 추출하여 별도 모듈에 배치, 해당 모듈에는 전문성이 없음

하위 도메인이 분리되고 나면 이후 개발은 CORE DOMAIN 보다 낮은 우선순위 부여
핵심 개발자를 배치하지 않음 (개발자가 도메인 지식을 얻지 못함)

기성 솔루션이나 공표된 모델을 고려

#### 예제
핵심이 아닌 시간대와 같은 것에 중요한 사람을 배치해선 안된다
❓ 443p 해운에서 불리한 점에 들어간 내용은 뭐지. 계약직이 했는데?

#### 보조적인 성격의 문서를 활용하기
DOMAIN VISION STATEMENT
HIGHLIGHTED CORE

### DOMAIN VISION STATEMENT
CORE DOMAIN 을 짧게 기술하고 가치에 해당하는 "가치 제안"을 작성

도메인 모델이 어떻게 다양한 관심사를 충족하고 균형을 이루는지

### HIGHLIGHTED CORE
CORE DOMAIN 을 잘 보이게끔
모든 사람이 CORE DOMAIN 을 쉽게 알 수 있게 하는 것

#### 디스틸레이션 문서
CORE DOMAIN 과 CORE 의 구성요소 사이에서 일어나는 상호작용을 매우 간결한 문서로 작성
비기술 팀원도 이해할 수 있는 문서

관리되지 않을 수도, 아무도 읽지 않을 수도, 문서가 복잡해질 수도 있음 (그래서 최소, 간결을 지향)

-> 예전부터 아이디어이긴 한데, 문서에 커밋 해시를 비교하게 해서 변경이 일어나면 문서도 같이 수정해야하는지 체크하는 기능이 있으면 좋을 것 같은데. 여기서 중요한 내용은 아니니 스킵

프로세스 도구로써 활용
모델 변경의 중요성을 나타내는 실질적인 지표

#### 표시된 (Flagged) CORE
모델 저장소에 있는 CORE DOMAIN 의 구성요소에 설명 말고 표시
개발자가 힘들이지 않고도 CORE 의 안/밖을 알 수 있게

### COHESIVE MECHANISM
how 에 대한 것을 lightweight framework 로 분리
INTENTION-REVEALING INTERFACE 로 프레임워크의 기능 노출

(생각) INTENTION-REVEALING INTERFACE 로 노출하는건 약간 [spring-data-commons](https://github.com/spring-projects/spring-data-commons) 와 실제 구현이 분리되어 있는 느낌

#### GENERIC SUBDOMAIN 과의 차이?
둘 다 CORE DOMAIN 의 부담을 덜어내지만, GS 는 도메인의 관점, CM 은 도메인이 아닌 계산 등

### SEGREGATED CORE
GENERIC SUBDOMAIN 을 추출하는 방식으로 도메인에서 일부 CORE 를 불분명하게 만드는 세부사항을 제거해 CORE 를 눈에 띄게

보조적인 역할에서 CORE 개념을 분리 -> CORE 와 다른 코드와의 결합을 줄임 -> CORE 의 응집력 강화

#### 개인적인 정리 - GENERIC SUBDOMAIN 과 SEGREGATED CORE 차이
GS 는 CORE 에서 표현하는 것과 거리가 먼 개념 (배송 알림 등)
SC 는 CORE 가 너무 클 때 뜯어내는 개념

### ABSTRACT CORE
수직적 (MODULE) 보단 수평적 (ABSTRACT) 으로 자르기

모델의 가장 근본적인 개념을 식별 -> 별도의 클래스 or abstract or interface 로 추출

#### 개인 의견
abstract class 에 들어가는건 별로인 것 같다
실제 어떤 값이 있는지가 구현한 클래스에서 바로 보이지 않음. ArticleVO 같은..

**Comment by bearics** [comment]
디스틸레이션 : CORE DOMAIN(문제의 본질)을 뽑아내는 과정

CORE DOMAIN
- 이해하기 쉽게 만들어야함 >> 리팩토링 유리

GENERIC SUBDOMAIN
- 코어의 복잡성을 줄이기 위해 응집력 있는 하위 도메인 식별
- 코어 도메인에 비해 낮은 우선순위, 핵심 개발자 배치 X

DOMAIN VISION STATEMENT
- 도메인 로드맵 << 만들고 싶다 ㅠㅠ

HIGHLIGHTED CORE

....작성중

**Comment by y2o2u2n** [comment]
- DISTILLATION :  혼합된 요소를 분리해서 본질을 좀더 값지고 유용한 형태로 뽑아내는 과정
- **CORE DOMAIN** : 가장 가치 있고 전문화된 개념을 담는 도메인
- GENERIC SUBDOMAIN : 현재 진행 중인 프로젝트를 위한 것이 아닌 하위 도메인. CORE DOMAIN 보다 낮은 우선순위
  - 고려해볼 선택지
    - 기성 솔루션
    - 공표된 설계나 모델
    - 외주제작된 구현
    - 사내 구현
- DOMAIN VISION STATEMENT : CORE DOMAIN 을 짧게 기술하고 그것이 가져올 가치에 해당하는 "가치 제안"을 담은 선언문
- HIGHLIGHTED CORE : CORE DOMAIN 을 표시해두는 것(?) 코드의 변경을 가하지 않고 정보를 제공하는 역할
- COHESIVE MECHANISM : "어떻게" 에 관련된 내용을 별도의 경량 프레임워크로 분할하고 INTENTION-REVEALING INTERFACE 로 프레임워크의 기능을 노출해서 사용하는 메커니즘
- SEGREGATED CORE : CORE 를 다른 코드와 결합을 줄이고 응집력을 강화하라는 말... 인 듯?
- ABSTRACT CORE : 복잡한 CORE 일 경우, 클래스 또는 추상 클래스 또는 인터페이스로 추출해서 사용하라는 듯
- 리팩터링 대상의 선택 : CORE 부터...!
