### ISSUE TITLE
2장 의사소통과 언어 사용

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#2]

**Comment by chanhyeong** [comment]
### UBIQUITOUS LANGUAGE
- 공통 언어가 없는 프로젝트
  - 개발자가 도메인 전문가(편의를 위해 이후 기획)를 위해 자신들의 언어를 번역해줘야 함
  - 기획도 개발자 간의, 다른 기획 간의 언어를 번역해줘야 함
  - 개발자들끼리도 서로 번역
- UBIQUITOUS LANGUAGE 를 구성하는 어휘에는 **클래스와 주요 연산의 이름**이 있음
- **UBIQUITOUS LANGUAGE 변화 = 모델의 변화**

#### 지속적으로 사용하다 모델의 취약점이 드러난 경우
1. 부자연스러운 것에 대한 대안 / 언어 공백이 발견 -> 토론 과정에서 **새로운 단어**
2. 도메인 모델의 변화로 인식
3. 용어의 의미가 바뀌면 팀에서는 클래스 다이어그램을 수정하고 클래스/메소드명 변경 + 동작 방식도 바꿈

---
### 생각
(결론: 기획/디자인과 개발이 사용하는 단어를 맞추자. -> 이 생각에 기반해서 아래)

1. 영어가 아닌 한국어에서 이 개념이 가능한가? (일단 한글 단어 -> 영단어로 기본적인 번역이 필요)
    - 메신저 상에 나온 얘기로는 `용어 사전` 같은게 관리되면 좋을 것으로 아이디어
    - 이렇게 되면 이거에 대한 관리 책임은 개발이 오롯이 하게 될 것 같음
2. 이걸 제대로 하려면 이 책의 1~3장은 기획/설계도 봐야하는 것 아닌가?
    - 글쓴이가 경험한 내용들을 공감할 듯

**Comment by y2o2u2n** [comment]
**보편 언어**

프로젝트에 사용하는 언어가 분열되면 문제가 발생한다.
다이어그램, 문서, 말할 때 항상 동일한 언어를 사용해야 하며, 부자연스러운 용어에 대해서 반대 의사를 내야 한다.

**Comment by youngvly** [comment]
Ubiquitous language에 대해서,
현재는 대부분 명시적인 용어사전은 없으나, 암묵적으로 개발/설계/서비스 모두 따라가는 용어들이 있는듯한데요,
개발 도중 설계및 서비스내 용어변경시, 개발도 용어변경을 따라가는게 맞을까요??
사이드이펙트로는 db,모델,서비스코드 등등 변경범위가 있다고 한다는 가정하에요 🤔
