### ISSUE TITLE
3장 모델과 구현의 연계

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#3]

**Comment by chanhyeong** [comment]
### MODEL-DRIVEN DESIGN
- 도메인 모델을 있는 그대로 반영 -> 설계와 모델의 대응을 분명하게
- 모델을 재검토 -> 더 자연스럽게 소프트웨어로 구현될 수 있게 수정
- 모델로부터 설계와 기본적인 책임 할당에 필요한 용어를 도출하자
- 구현을 모델과 묶으려면 OOP 와 같은 모델링 패러다임을 지원하는 소프트웨어 개발 도구와 언어가 필요

### HANDS-ON MODELER
개발자는
1. 코드를 접하는 데 어느 정도 시간을 투자해야 한다
2. 코드를 통해 모델을 표현하는 법을 배워야 한다
3. 모델에 관한 토의에 깊이 관여하고 도메인 전문가와도 접촉해야 한다
4. UBIQUITOUS LANGUAGE 를 토대로 모델의 아이디어를 나눠야 한다

**Comment by y2o2u2n** [comment]
도메인 모델을 있는 그대로 반영해서 설계와 모델의 대응을 분명하게 하라

모델에 기여하는 모든 기술자들이 역할에 상관 없이 해당 모델을 잘 알고 있어야 한다.
그렇지 않으면 담겨 있는 핵심 도메인 지식이 금방 무너지게 된다.

**Comment by bearics** [comment]
개발 특성상, 핵심 도메인 지식을 가지고 있는 개발자가 계속 개발에 참여하는 경우는 어렵기 때문에
이를 효과적으로 공유할 수 있는 방법이 있을까요? << 현재 이거 하고 있나요??
