### ISSUE TITLE
로그인 구현하기

### ISSUE THREAD

**Issue by youngvly** [juniors-dev-study/domain-driven-design#31]

**Comment by youngvly** [comment]
- loginUser에서 user 내용 펼치기
- controller에서 loginUser 객체로 바로 받을수있는지 확인
- 로그인 api 구현
- 
- 로그인 화면 구현

**Comment by youngvly** [comment]
로그인정보를 다른 모듈에서도 사용할수있도록, 인증값 생성하는 서버 필요.
- oauth2.0 / JWT 응용
   - user-api, ..등의 도메인을 가지는 모듈은 동일한 레이어상에 있어야하고, 인증토큰 생성은 인프라레벨, 별도 인증서버로 생성한다.
- User서버와 동일한 데이터 소스를 가지고 사용. Only read
csrf https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#mvc-csrf-resolver

**Comment by youngvly** [comment]
1. refresh_token
2. test

**Comment by chanhyeong** [comment]
클라우드 네이티브 패턴이라는 책을 보는데 시작 부분에 이런게 있긴 하네요

![image](https://drek4537l1klr.cloudfront.net/cdavis/Figures/01fig09_alt.jpg)
