### ISSUE TITLE
5장 소프트웨어에서 표현되는 모델

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#5]

**Comment by y2o2u2n** [comment]
**엔티티 VS 값 객체**

어떤 객체가 연속성 & 식별성 을 지녔다면 전자,
단순히 뭔가의 상태를 기술하는 속성에 불과하다면 후자

**연관관계**

연관 관계를 쉽게 다루려면 아래 3가지를 고려해라

- 탐색 방향을 부여한다
- 한정자를 추가해서 사실상 다중성을 줄인다
- 중요하지 않은 연관 관계를 제거한다

현실 세계에서는 양방향으로 보이는 관계가 애플리케이션 요구사항에서는 그렇지 않을 수 있다.
요구사항에 없는 관계라면 제거하면 의존성이 줄고 설계가 단순해진다.

**엔티티**

자신의 생명주기 동안 형태와 내용이 바뀔 수도 있지만 연속성은 유지하며,
추적할 수 있게 식별성이 정의되어 있는 객체

- 엔티티 모델링
  - 엔티티 개념에 필수적인 행위만 추가하고 그 행위에 필요한 속성만 추가한다. 
  - 그 외는 연관관계의 다른 객체(엔티티 또는 값 객체)로 옮긴다.
- 식별 연산의 설계
  - 시스템에서 ID 를 자동으로 만들어 낸다면 그것을 사용하면 됨 (예. DB)
  - 병행 처리 시스템이나 분산 시스템에서는 쉽지 않은 문제일 수 있음

**값 객체**

식별성이 없는 객체. 사물의 어떤 특징을 묘사함.
모델에 포함된 어떤 요소의 속성에만 관심 있다면 값 객체.
불변적으로 다루고 식별성을 부여하지 말아라.
값 객체에게 양방향 관계는 의미가 없다.

**서비스**

도메인의 개념 가운데 엔티티 또는 값 객체에 어울리지 않는 활동 또는 행동이 있을 때,
이를 무리하게 엔티티 또는 값 객체에 넣지 않고 서비스에서 사용한다.

잘 만들어진 서비스는 아래와 같다.

1. 연산이 원래부터 엔티티나 값 객체의 일부를 구성하는 것이 아니라 도메인 개념과 관련이 있다.
2. 인터페이스가 도메인 모델의 외적 요쇼의 측면에서 정의된다.
3. 연산이 상태를 갖지 않는다.

서비스는 응용, 도메인, 인프라스트럭처 계층으로 나뉠 수 있다.

**모듈**

모듈 간 결합도가 낮아야 하고 모듈 내부는 응집도가 높아야 한다.
일련의 응집력 있는 개념들을 한 모듈에 담고 낮은 결합도가 달성되도록 노력해야 한다.
모듈의 이름은 보편 언어로 구성해라.

---

**생각**

- 엔티티의 '연속성'이라는 의미가 무엇인지 모르겠다.
- 서비스의 여러 계층의 예시는 어떤 것이 있는지 궁금하다.

**Comment by chanhyeong** [comment]
각자가 생각하는 이상적인 MODULE 구조?
- 상담
- 빵틀
- 알림

**Comment by chanhyeong** [comment]
### SERVICE
(spring 의 `@Service` 도 여기서 가져옴)

도메인 개념 중 객체로는 모델에 어울리지 않는 것
SERVICE 는 layer 각각에 속할 수 있다

(4장에서의 개념을 같이 보면서) 각 layer 아래에는 기존 구현이 왜 이렇게 들어갔는지에 대한 의문

1. application
    - controller 는 여기가 아닌가? 왜 infra 에 들어가있는지
2. domain
    - commands, queries 는 여기가 아닌가? 왜 application 에 들어가 있는지
    - repository 도 interface 이긴 하고 실제 구현은 infra 긴 하지만, 애초에 infra 로 들어가야 하는거 아닌지
3. infra

**Comment by bearics** [comment]
p111
응용 서비스, 도메인 서비스를 다른 package로 분리? 

```
application-service
                   .a.service
                   .b.service

domain.
       account
                     .infra
                     .service
       person
                   .infra
                   .service
```

**Comment by youngvly** [comment]
- 응용계층 서비스 : 클라이언트의 요청에 대해 수행되는 무언가
- 도메인계층 서비스 : 상태를 주고받지않는 활동을 모델링하는 경우..❓
그럼 직접적인 도메인객체 호출은 도메인 계층에서 하고, 응용계층 서비스는 각 도메인계층서비스를 호출하는건지.. 둘의 차이가 헷갈리네요
