### ISSUE TITLE
7장 언어의 사용(확장 예제)

### ISSUE THREAD

**Issue by y2o2u2n** [juniors-dev-study/domain-driven-design#7]

**Comment by chanhyeong** [comment]
따로 코멘트 할건 없음
책 내용 순서대로 요약한거 [링크](https://github.com/chanhyeong/study/blob/main/ddd/7_using_language.md)

**Comment by bearics** [comment]
## 7장 언어의 사용(확장 예제)

![image](https://user-images.githubusercontent.com/7814414/127521657-82d8afdc-a42e-474a-bfde-dbf47ee8fd17.png)
**도메인 격리(응용 기능 소개) = layered architecture**

1. Tracking Query(추적 질의) : 특정 cargo의 과거와 현재 처리 상태 조회
2. Booking Application(예약 애플리케이션) : new cargo 등록 & 등록된 cargo 처리 준비
3. Incident Logging Application(사건 기록 애플리케이션) : 각 cargo 내역 기록

이 응용 계층의 클래스 = 조정자(coordinator)

**ENTITY & VO 구분**

Customer : ID 식별성 O > ENTITY

Cargo : 여러 Cargo 구분 필요. ID 식별성 O > ENTITY

Handling Event & Carrier Movement : 사건 구분 필요. 식별성 O > ENTITY

Location : 식별성 필요. > ENTITY

Delivery History* : Cargo와 일대일 관계라 식별성 필요?

Delivery Specification :  > VO

**도메인의 연관관계 설계**

![image](https://user-images.githubusercontent.com/7814414/127521702-bbb19ab1-0360-4999-bf07-c5dbc6c4dbde.png)
- Cago > Customer 관계인데, Repository를 이용해 다른 방향으로 접근 할 수 있다?
    - class 간의 관계은 Cargo > Customer로 두고, DB select으로 반대로 접근 할 수 있다는건가?
- Location과 같은 기본적인 ENTITY는...
    - 이것도 엔티티인가요?
- 이러한 관계들은 이상적인 설계도 중요하지만, 성능도 무시할 수 없음(포인터를 어디 클래스에 두느냐.. 등)

**AGGREGATE의 경계**

![image](https://user-images.githubusercontent.com/7814414/127521743-73794801-ba37-4c78-8a04-f1e1c54119e1.png)

- customer, location, carrier movement 자체 식별성이 있고, 
여러 cargo에서 공유되기에 자체 AGG의 루트
- cargo's AGG
    - Delivery History, Delivery Specification : cargo가 없으면 의미 없는 것들은 같은 AGG로 묶기
    - Handling Event : Carrier Movement의 이벤트를 조회해야 할 수 있어서 따로 빼는것이 좋을듯

**REPOSITORY의 선정**

![image](https://user-images.githubusercontent.com/7814414/127521775-43cf8026-a939-4c44-a90f-3648aca0bcc6.png)
- handling event는 delivery history의 컬렉션으로 유지 하기에 따로 REPO X

**객체 생성**

- Handling Event를 추가하게 되면, Cargo의 delivery History까지 업데이트 해줘야함.
이는 Handling Event 생성 과정에 Cargo까지 트랜잭션으로 묶여야 한다
    - 이를 해결하기 위해 컬랙션 관계 > 질의로 교체 & Hadling Event REPO 추가

**MODULE**

![image](https://user-images.githubusercontent.com/7814414/127521513-716cc073-0703-4253-a63d-3e0214c85b36.png)

업무 분야에 따라 관계에 따라 잘 나눠야 한다.

새로운 기능 추가

![image](https://user-images.githubusercontent.com/7814414/127521561-d715d2bc-4a11-4199-8156-904fca446623.png)

무슨 소리지..?

**Comment by y2o2u2n** [comment]
제가 이해한 절차는 아래와 같긴 합니다.
근데 책 사례는 잘 이해 안가요 🤮

1. 도메인 지식 탐구, 보편 언어 구체화
2. 도메인 계층 식별
3. ENTITY 와 VALUE OBJECT 구분
4. 연관관계 설계
5. AGGREGATE 경계 긋기
6. REPOSITORY 선정
7. FACTORY 도입 검토
8. MODULE 분리

* 각 단계마다 계속 리뷰해보고 문제를 효과적으로 해결하는지 확인

**Comment by youngvly** [comment]
🤮 
Aggregate root Entity만 repository를 가질수있다고 한다는데, 그럼 cargo-history와같은 다른 entity는 어떻게 db에서 가져오는걸까요?.
handlingEvent랑 cargo history랑 의미나 역할차이를 모르겠네요 ㅜ

**Comment by bearics** [comment]
다음은 8,9 장
