### ISSUE TITLE
8장 도약

### ISSUE THREAD

**Issue by youngvly** [juniors-dev-study/domain-driven-design#9]
# 08 도약
 - 심층 모델 : 도메인의 피상적인 측면은 배제하고, 도메인 전문가의 주요 관심사와 가장 적절한 지식을 알기쉽게 표현하는 모델이다. 이 정의가 추상화를 의미하는것은 아니다.

 ### 초반 모델
<img width="788" alt="스캔한 페이지" src="https://user-images.githubusercontent.com/19251378/127865825-67db5da8-be54-4f98-be8d-b4d16fbc8ae8.png">
  - loan adjustment : 대출사간의 대출금 지불 참여 지분조정 
  - 요청사항이 추가될수록 복잡도가 증가.

 ### 리팩토링 후 모델
<img width="720" alt="스캔한 페이지" src="https://user-images.githubusercontent.com/19251378/127869140-4526e7e9-540e-4018-b115-1f81f5f328e3.png">

- 심층모델을 뽑아내려면 (도약하려면?) 
   1. 지식탐구, Ubiquitous language 만드는 일에 집중.
   2. 중요한 도메인 개념조사하고 모델내에 명시적으로 표현.
   3. 유연해지도록 설계를 정제한다.'
   4. 모델의 정수를 추출한다.

**Comment by y2o2u2n** [comment]
**리팩터링**

- 소프트웨어의 기능을 수정하지 않고 설계를 다시 하는 것
- 기술적으로 코드의 상태를 개선하기보다는 도메인 모델을 더 잘 만들기 위해서 하는 것이 좋음

**도약**

- 리팩터리의 효과는 선형적으로 증가하지 않음
- 인내심을 가지고 지식탐구, 보편언어 만들기에 집중해야 함

**Comment by chanhyeong** [comment]
#### 심층 모델 (Deep model)
- 도메인 전문가의 주요 관심사와 가장 적절한 지식을 알기 쉽게 표현하는 모델
  -  단순히 명사는 객체 이름, 동사는 메소드가 아님
- 지속적인 리팩토링을 수행하려면 설계 자체가 변경을 지원해야 한다
- 유연한 설계 -> 변경을 촉진하고 모델 개선에 기여
- 설계에 표현력을 부여

#### 도약
- 심층 모델은 소규모 리팩토링 과정을 거쳐 서서히 드러난다
- **사건**
- 기본에 집중하자
  - 수많은 적정 규모의 리팩토링이 있어야 함
  - 지식탐구 + UBIQUITOUS LANGUAGE 를 만드는 일에 집중
  - 중요한 도메인 개념을 조사하고, 모델 내에 명시적으로 표현한다 (9장)
  - 유연해지도록 설계를 정제한다 (10장)
  - 모델의 정수를 추출한다 (15장)

---

외국도 일정 + 정치가..

**Comment by bearics** [comment]
UML 화살표
![image](https://user-images.githubusercontent.com/7814414/128385363-bde64bec-e58e-4488-ac42-65a99dee9701.png)

리팩토링하면서 모델 구조도 바뀔 수 있음. << 가능한건가??
